import React from "react";
import type { Metadata } from "next";
// eslint-disable-next-line camelcase
import { JetBrains_Mono } from "next/font/google";
import { Providers } from "@/providers/WalletConntectionProvider";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "CTRL",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.className + " bg-black"}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
